apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kuweb-hpa
spec:
  minReplicas: 3
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kuweb-deployment
  targetCPUUtilizationPercentage: 5