FROM openjdk:11
LABEL maintainer "kh<ismoon@iei.com>"
LABEL version="1.0"
COPY 05_SpringBoot_MVC-0.0.1-SNAPSHOT.jar /root
ENV TZ=Asia/Seoul
WORKDIR /root
EXPOSE 8088
CMD ["java", "-jar", "05_SpringBoot_MVC-0.0.1-SNAPSHOT.jar", "--spring.profiles.active=dev"]