-- 큐티마켓 스크립트

------------------------------------------------
------------------- 테이블 생성 ------------------
------------------------------------------------
-- QT_USER 테이블 생성
CREATE TABLE QT_USER (
	USER_ID VARCHAR2(20) NOT NULL,
	USER_PASSWORD VARCHAR2(100) NOT NULL,
	USER_NAME VARCHAR2(20) NOT NULL,
	USER_EMAIL VARCHAR2(50) NOT NULL,
    ORIGINAL_PROFILENAME VARCHAR2(100), 
	RENAMED_PROFILENAME VARCHAR2(100),
	USER_PHONE VARCHAR2(20) NOT NULL,
	USER_ROLE VARCHAR2(10) DEFAULT 'ROLE_USER',
	USER_ENROLLDATE	DATE DEFAULT SYSDATE,
	USER_AREA1 VARCHAR2(20),
    USER_AREA2 VARCHAR2(20)
);

-- BOARD 테이블 생성
CREATE TABLE BOARD (
	BOARD_NO NUMBER,
	USER_ID VARCHAR2(20),
	BOARD_TITLE VARCHAR2(100),
	BOARD_CONTENT VARCHAR2(4000),
	BOARD_CREATED DATE DEFAULT SYSDATE,
	BOARD_MODIFIED DATE DEFAULT SYSDATE,
	BOARD_HITS NUMBER DEFAULT 0,
    ORIGINAL_FILENAME VARCHAR2(100), 
	RENAMED_FILENAME VARCHAR2(100),
    CATEGORY VARCHAR2(30)
);

-- BOARD_COMMENT 테이블 생성
CREATE TABLE BOARD_COMMENT (
	COMMENT_NO NUMBER,
	BOARD_NO NUMBER,
	USER_ID VARCHAR2(20),
	COMMENT_CONTENT VARCHAR2(1000),
	B_COMMENT_CREATED DATE DEFAULT SYSDATE,
	B_COMMENT_MODIFIED DATE DEFAULT SYSDATE
);


-- GOODS 테이블 생성
CREATE TABLE GOODS (
	G_PRODUCT NUMBER NOT NULL,
	USER_ID	VARCHAR2(20) NOT NULL,
	G_PRODUCT_NAME VARCHAR2(100) NOT NULL,
	G_PRICE	VARCHAR2(20) NOT NULL,
	G_CONTENT VARCHAR2(4000) NOT NULL,
	G_DATE DATE DEFAULT SYSDATE,
	G_HITS NUMBER DEFAULT 0,
	G_CATE VARCHAR(20),
    G_O_FILENAME VARCHAR2(100),
    G_R_FILENAME VARCHAR2(100),
    G_AREA1 VARCHAR2(20),
    G_AREA2 VARCHAR2(20),
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK(STATUS IN('Y', 'N'))
);

-- GOODS_COMMENT 테이블 생성
CREATE TABLE GOODS_COMMENT (
	G_COMMENT_NO NUMBER	NOT NULL,
	G_PRODUCT NUMBER NOT NULL,
	G_BOARD_CONTENT	VARCHAR2(1000) NOT NULL,
	G_WRITER_ID	VARCHAR2(20) NOT NULL,
	G_COMMENT_CREATED DATE DEFAULT SYSDATE,
	G_COMMENT_MODIFIED DATE DEFAULT SYSDATE
);

-- GOODS_WISHLIST 테이블 생성
CREATE TABLE GOODS_WISHLIST (
	G_PRODUCT NUMBER NOT NULL,
	USER_ID	VARCHAR2(20) NOT NULL
);


------------------------------------------------
--------------------- 코멘트 --------------------
------------------------------------------------
-- QT_USER 테이블 COMMENT 추가
COMMENT ON COLUMN QT_USER.USER_ID IS '아이디';
COMMENT ON COLUMN QT_USER.USER_PASSWORD IS '비밀번호';
COMMENT ON COLUMN QT_USER.USER_NAME IS '이름';
COMMENT ON COLUMN QT_USER.USER_EMAIL IS '이메일';
COMMENT ON COLUMN QT_USER.ORIGINAL_PROFILENAME IS '원본프로필사진';
COMMENT ON COLUMN QT_USER.RENAMED_PROFILENAME IS '수정프로필사진';
COMMENT ON COLUMN QT_USER.USER_PHONE IS '전화번호';
COMMENT ON COLUMN QT_USER.USER_ROLE IS '유저권한';
COMMENT ON COLUMN QT_USER.USER_ENROLLDATE IS '가입날짜';
COMMENT ON COLUMN QT_USER.USER_AREA1 IS '시/도';
COMMENT ON COLUMN QT_USER.USER_AREA2 IS '구/군';

-- BOARD 테이블 COMMENT 추가
COMMENT ON COLUMN BOARD.BOARD_NO IS '글번호';
COMMENT ON COLUMN BOARD.USER_ID IS '아이디';
COMMENT ON COLUMN BOARD.BOARD_TITLE IS '제목';
COMMENT ON COLUMN BOARD.BOARD_CONTENT IS '글내용';
COMMENT ON COLUMN BOARD.BOARD_CREATED IS '작성일';
COMMENT ON COLUMN BOARD.BOARD_MODIFIED IS '수정일';
COMMENT ON COLUMN BOARD.BOARD_HITS IS '조회수';
COMMENT ON COLUMN BOARD.ORIGINAL_FILENAME IS '원본파일';
COMMENT ON COLUMN BOARD.RENAMED_FILENAME IS '서버파일';
COMMENT ON COLUMN BOARD.CATEGORY IS '게시판 카테고리';

-- BOARD_COMMENT 테이블 COMMENT 추가
COMMENT ON COLUMN BOARD_COMMENT.COMMENT_NO IS '댓글번호';
COMMENT ON COLUMN BOARD_COMMENT.BOARD_NO IS '글번호';
COMMENT ON COLUMN BOARD_COMMENT.USER_ID IS '댓글회원ID';
COMMENT ON COLUMN BOARD_COMMENT.COMMENT_CONTENT IS '댓글내용';
COMMENT ON COLUMN BOARD_COMMENT.B_COMMENT_CREATED IS '댓글작성일';
COMMENT ON COLUMN BOARD_COMMENT.B_COMMENT_MODIFIED IS '댓글수정일';

-- GOODS 테이블 COMMENT 추가
COMMENT ON COLUMN GOODS.G_PRODUCT IS '상품번호';
COMMENT ON COLUMN GOODS.USER_ID IS '아이디';
COMMENT ON COLUMN GOODS.G_PRODUCT_NAME IS '상품명';
COMMENT ON COLUMN GOODS.G_PRICE IS '가격';
COMMENT ON COLUMN GOODS.G_CONTENT IS '내용';
COMMENT ON COLUMN GOODS.G_DATE IS '작성일';
COMMENT ON COLUMN GOODS.G_HITS IS '조회수';
COMMENT ON COLUMN GOODS.G_CON IS '상품상태';
COMMENT ON COLUMN GOODS.G_CATE IS '카테고리';
COMMENT ON COLUMN GOODS.G_O_FILENAME IS '첨부파일원래이름';
COMMENT ON COLUMN GOODS.G_R_FILENAME IS '첨부파일변경이름';
COMMENT ON COLUMN GOODS.G_AREA1 IS '시';
COMMENT ON COLUMN GOODS.G_AREA2 IS '동';
COMMENT ON COLUMN GOODS.STATUS IS '상태';

-- GOODS_COMMENT 테이블 COMMENT 추가
COMMENT ON COLUMN GOODS_COMMENT.G_COMMENT_NO IS '댓글번호';
COMMENT ON COLUMN GOODS_COMMENT.G_PRODUCT IS '상품번호';
COMMENT ON COLUMN GOODS_COMMENT.G_BOARD_CONTENT IS '내용';
COMMENT ON COLUMN GOODS_COMMENT.G_WRITER_ID IS '댓글회원ID';
COMMENT ON COLUMN GOODS_COMMENT.G_COMMENT_CREATED IS '댓글작성일';
COMMENT ON COLUMN GOODS_COMMENT.G_COMMENT_MODIFIED IS '댓글수정일';

-- GOODS_WISHLIST 테이블 COMMENT 추가
COMMENT ON COLUMN GOODS_WISHLIST.G_PRODUCT IS '상품번호';
COMMENT ON COLUMN GOODS_WISHLIST.USER_ID IS '아이디';


------------------------------------------------
--------------------- 제약조건 --------------------
------------------------------------------------
-- QT_USER 테이블 제약조건 추가
ALTER TABLE QT_USER ADD CONSTRAINT PK_QT_USER PRIMARY KEY (USER_ID);

-- BOARD 테이블 제약조건 추가
ALTER TABLE BOARD ADD CONSTRAINT BOARD_BOARD_NO_PK PRIMARY KEY(BOARD_NO);
ALTER TABLE BOARD ADD CONSTRAINT BOARD_USER_ID_FK FOREIGN KEY(USER_ID) REFERENCES QT_USER (USER_ID) ON DELETE CASCADE;

-- BOARD_COMMENT 테이블 제약조건 추가
ALTER TABLE BOARD_COMMENT ADD CONSTRAINT BOARD_COMMENT_COMMENT_NO_PK PRIMARY KEY(COMMENT_NO);
ALTER TABLE BOARD_COMMENT ADD CONSTRAINT BOARD_COMMENT_BOARD_NO_FK FOREIGN KEY(BOARD_NO) REFERENCES BOARD (BOARD_NO) ON DELETE CASCADE;
ALTER TABLE BOARD_COMMENT ADD CONSTRAINT BOARD_COMMENT_USER_ID_FK FOREIGN KEY(USER_ID) REFERENCES QT_USER (USER_ID) ON DELETE CASCADE;


-- GOODS 테이블 제약조건 추가
ALTER TABLE GOODS ADD CONSTRAINT GOODS_G_PRODUCT_PK PRIMARY KEY(G_PRODUCT);

-- GOODS_COMMENT 테이블 제약조건 추가
ALTER TABLE GOODS_COMMENT ADD CONSTRAINT GOODS_COMMENT_PK PRIMARY KEY(G_COMMENT_NO);
ALTER TABLE GOODS_COMMENT ADD CONSTRAINT GOODS_TO_GOODS_COMMENT_FK FOREIGN KEY(G_PRODUCT) REFERENCES GOODS (G_PRODUCT)ON DELETE CASCADE;

-- GOODS_WISHLIST 테이블 제약조건 추가
ALTER TABLE GOODS_WISHLIST ADD CONSTRAINT GOODS_WISHLIST_PK2 PRIMARY KEY(G_PRODUCT, USER_ID);
ALTER TABLE GOODS_WISHLIST ADD CONSTRAINT GOODS_TO_GOODS_WISHLIST_FK FOREIGN KEY(G_PRODUCT) REFERENCES GOODS (G_PRODUCT)ON DELETE CASCADE;
ALTER TABLE GOODS_WISHLIST ADD CONSTRAINT QT_TO_GOODS_WISHLIST_FK FOREIGN KEY(USER_ID) REFERENCES QT_USER (USER_ID)ON DELETE CASCADE;


------------------------------------------------
--------------------- 시퀀스 --------------------
------------------------------------------------


-- 굿즈 시퀀스 생성
CREATE SEQUENCE SEQ_GOODS_NO;
CREATE SEQUENCE SEQ_REPLY_NO;

-- 보드 시퀀스 생성
CREATE SEQUENCE SEQ_BOARD_NO;

-- 보드_코멘트 시퀀스 생성
CREATE SEQUENCE SEQ_COMMENT_NO;


------------------------------------------------
--------------- 더미 데이터 (관리자)---------------
------------------------------------------------

INSERT INTO QT_USER (
    USER_ID,
    USER_PASSWORD,
    USER_NAME,
    USER_EMAIL,
    ORIGINAL_PROFILENAME,
    RENAMED_PROFILENAME,
    USER_PHONE,
    USER_ROLE,
    USER_ENROLLDATE,
    USER_AREA1,
    USER_AREA2
) VALUES (
    'admin1',
    '1234',
    '서수민',
    'ssm@naver.com',
    'profile1.jpg',
    'profile2.jpg',
    '010-8864-5742',
    'ROLE_ADMIN',
    DEFAULT,
    '서울특별시',
    '강남구'
);



INSERT INTO QT_USER (
    USER_ID,
    USER_PASSWORD,
    USER_NAME,
    USER_EMAIL,
    ORIGINAL_PROFILENAME,
    RENAMED_PROFILENAME,
    USER_PHONE,
    USER_ROLE,
    USER_ENROLLDATE,
    USER_AREA1,
    USER_AREA2
) VALUES (
    'admin2',
    '1234',
    '임현규',
    'lhg@naver.com',
    'profile1.jpg',
    'profile2.jpg',
    '010-1234-5678',
    'ROLE_ADMIN',
    DEFAULT,
    '서울특별시',
    '강남구'
);



INSERT INTO QT_USER (
    USER_ID,
    USER_PASSWORD,
    USER_NAME,
    USER_EMAIL,
    ORIGINAL_PROFILENAME,
    RENAMED_PROFILENAME,
    USER_PHONE,
    USER_ROLE,
    USER_ENROLLDATE,
    USER_AREA1,
    USER_AREA2
) VALUES (
    'admin3',
    '1234',
    '이산아',
    'lsa@naver.com',
    'profile1.jpg',
    'profile2.jpg',
    '010-1234-5678',
    'ROLE_ADMIN',
    DEFAULT,
    '서울특별시',
    '강남구'
);



INSERT INTO QT_USER (
    USER_ID,
    USER_PASSWORD,
    USER_NAME,
    USER_EMAIL,
    ORIGINAL_PROFILENAME,
    RENAMED_PROFILENAME,
    USER_PHONE,
    USER_ROLE,
    USER_ENROLLDATE,
    USER_AREA1,
    USER_AREA2
) VALUES (
    'admin4',
    '1234',
    '김성엽',
    'ksy@naver.com',
    'profile1.jpg',
    'profile2.jpg',
    '010-1234-5678',
    'ROLE_ADMIN',
    DEFAULT,
    '서울특별시',
    '강남구'
);

INSERT INTO QT_USER (
    USER_ID,
    USER_PASSWORD,
    USER_NAME,
    USER_EMAIL,
    ORIGINAL_PROFILENAME,
    RENAMED_PROFILENAME,
    USER_PHONE,
    USER_ROLE,
    USER_ENROLLDATE,
    USER_AREA1,
    USER_AREA2
) VALUES (
    'admin5',
    '1234',
    '맹세정',
    'msg@naver.com',
    'profile1.jpg',
    'profile2.jpg',
    '010-1234-5678',
    'ROLE_ADMIN',
    DEFAULT,
    '서울특별시',
    '강남구'
);


COMMIT;


------------------------------------------------
--------------- 더미 데이터 (유저)---------------
------------------------------------------------

SET DEFINE OFF;

Insert into QT_USER (USER_ID,USER_PASSWORD,USER_NAME,USER_EMAIL,ORIGINAL_PROFILENAME,RENAMED_PROFILENAME,USER_PHONE,USER_ROLE,USER_ENROLLDATE,USER_AREA1,USER_AREA2) values ('user1','1234','송한나','shn@naver.com','profile1.jpg','profile1.jpg','010-1234-5678','ROLE_USER',to_date('21/12/21','RR/MM/DD'),'부산특별시','해운대구');
Insert into QT_USER (USER_ID,USER_PASSWORD,USER_NAME,USER_EMAIL,ORIGINAL_PROFILENAME,RENAMED_PROFILENAME,USER_PHONE,USER_ROLE,USER_ENROLLDATE,USER_AREA1,USER_AREA2) values ('user2','1234','송하은','she@naver.com','profile1.jpg','profile1.jpg','010-1234-5678','ROLE_USER',to_date('21/12/21','RR/MM/DD'),'부산특별시','해운대구');
Insert into QT_USER (USER_ID,USER_PASSWORD,USER_NAME,USER_EMAIL,ORIGINAL_PROFILENAME,RENAMED_PROFILENAME,USER_PHONE,USER_ROLE,USER_ENROLLDATE,USER_AREA1,USER_AREA2) values ('user3','1234','송진한','she@naver.com','profile1.jpg','profile1.jpg','010-1234-5678','ROLE_USER',to_date('21/12/21','RR/MM/DD'),'부산특별시','수영구');
Insert into QT_USER (USER_ID,USER_PASSWORD,USER_NAME,USER_EMAIL,ORIGINAL_PROFILENAME,RENAMED_PROFILENAME,USER_PHONE,USER_ROLE,USER_ENROLLDATE,USER_AREA1,USER_AREA2) values ('user4','1234','황규성','she@naver.com','profile1.jpg','profile1.jpg','010-1234-5678','ROLE_USER',to_date('21/12/21','RR/MM/DD'),'부산특별시','수영구');
Insert into QT_USER (USER_ID,USER_PASSWORD,USER_NAME,USER_EMAIL,ORIGINAL_PROFILENAME,RENAMED_PROFILENAME,USER_PHONE,USER_ROLE,USER_ENROLLDATE,USER_AREA1,USER_AREA2) values ('user5','1234','고들비','she@naver.com','profile1.jpg','profile1.jpg','010-1234-5678','ROLE_USER',to_date('21/12/21','RR/MM/DD'),'부산특별시','수영구');
Insert into QT_USER (USER_ID,USER_PASSWORD,USER_NAME,USER_EMAIL,ORIGINAL_PROFILENAME,RENAMED_PROFILENAME,USER_PHONE,USER_ROLE,USER_ENROLLDATE,USER_AREA1,USER_AREA2) values ('user6','1234','서인빈','she@naver.com','profile1.jpg','profile1.jpg','010-1234-5678','ROLE_USER',to_date('21/12/21','RR/MM/DD'),'부산특별시','수영구');
Insert into QT_USER (USER_ID,USER_PASSWORD,USER_NAME,USER_EMAIL,ORIGINAL_PROFILENAME,RENAMED_PROFILENAME,USER_PHONE,USER_ROLE,USER_ENROLLDATE,USER_AREA1,USER_AREA2) values ('user7','1234','박승우','she@naver.com','profile1.jpg','profile1.jpg','010-1234-5678','ROLE_USER',to_date('21/12/21','RR/MM/DD'),'경기도','파주시');
Insert into QT_USER (USER_ID,USER_PASSWORD,USER_NAME,USER_EMAIL,ORIGINAL_PROFILENAME,RENAMED_PROFILENAME,USER_PHONE,USER_ROLE,USER_ENROLLDATE,USER_AREA1,USER_AREA2) values ('user8','1234','신문규','she@naver.com','profile1.jpg','profile1.jpg','010-1234-5678','ROLE_USER',to_date('21/12/21','RR/MM/DD'),'부산광역시','강서구');
Insert into QT_USER (USER_ID,USER_PASSWORD,USER_NAME,USER_EMAIL,ORIGINAL_PROFILENAME,RENAMED_PROFILENAME,USER_PHONE,USER_ROLE,USER_ENROLLDATE,USER_AREA1,USER_AREA2) values ('user9','1234','엄세영','she@naver.com','profile1.jpg','profile1.jpg','010-1234-5678','ROLE_USER',to_date('21/12/21','RR/MM/DD'),'인천광역시','부평구');
Insert into QT_USER (USER_ID,USER_PASSWORD,USER_NAME,USER_EMAIL,ORIGINAL_PROFILENAME,RENAMED_PROFILENAME,USER_PHONE,USER_ROLE,USER_ENROLLDATE,USER_AREA1,USER_AREA2) values ('user10','1234','김도헌','she@naver.com','profile1.jpg','profile1.jpg','010-1234-5678','ROLE_USER',to_date('21/12/21','RR/MM/DD'),'경기도','광주시');
Insert into QT_USER (USER_ID,USER_PASSWORD,USER_NAME,USER_EMAIL,ORIGINAL_PROFILENAME,RENAMED_PROFILENAME,USER_PHONE,USER_ROLE,USER_ENROLLDATE,USER_AREA1,USER_AREA2) values ('user11','1234','함성원','she@naver.com','profile1.jpg','profile1.jpg','010-1234-5678','ROLE_USER',to_date('21/12/21','RR/MM/DD'),'부산광역시','중구');
Insert into QT_USER (USER_ID,USER_PASSWORD,USER_NAME,USER_EMAIL,ORIGINAL_PROFILENAME,RENAMED_PROFILENAME,USER_PHONE,USER_ROLE,USER_ENROLLDATE,USER_AREA1,USER_AREA2) values ('user12','1234','박창욱','she@naver.com','profile1.jpg','profile1.jpg','010-1234-5678','ROLE_USER',to_date('21/12/21','RR/MM/DD'),'부산광역시','수영구');
Insert into QT_USER (USER_ID,USER_PASSWORD,USER_NAME,USER_EMAIL,ORIGINAL_PROFILENAME,RENAMED_PROFILENAME,USER_PHONE,USER_ROLE,USER_ENROLLDATE,USER_AREA1,USER_AREA2) values ('user13','1234','김재은','she@naver.com','profile1.jpg','profile1.jpg','010-1234-5678','ROLE_USER',to_date('21/12/21','RR/MM/DD'),'서울특별시','성북구');
Insert into QT_USER (USER_ID,USER_PASSWORD,USER_NAME,USER_EMAIL,ORIGINAL_PROFILENAME,RENAMED_PROFILENAME,USER_PHONE,USER_ROLE,USER_ENROLLDATE,USER_AREA1,USER_AREA2) values ('user14','1234','황주용','she@naver.com','profile1.jpg','profile1.jpg','010-1234-5678','ROLE_USER',to_date('21/12/21','RR/MM/DD'),'부산광역시','수영구');
Insert into QT_USER (USER_ID,USER_PASSWORD,USER_NAME,USER_EMAIL,ORIGINAL_PROFILENAME,RENAMED_PROFILENAME,USER_PHONE,USER_ROLE,USER_ENROLLDATE,USER_AREA1,USER_AREA2) values ('user15','1234','김동휘','she@naver.com','profile1.jpg','profile1.jpg','010-1234-5678','ROLE_USER',to_date('21/12/21','RR/MM/DD'),'경상남도','진주시');
Insert into QT_USER (USER_ID,USER_PASSWORD,USER_NAME,USER_EMAIL,ORIGINAL_PROFILENAME,RENAMED_PROFILENAME,USER_PHONE,USER_ROLE,USER_ENROLLDATE,USER_AREA1,USER_AREA2) values ('user16','1234','배종현','she@naver.com','profile1.jpg','profile1.jpg','010-1234-5678','ROLE_USER',to_date('21/12/21','RR/MM/DD'),'서울특별시','강동구');
Insert into QT_USER (USER_ID,USER_PASSWORD,USER_NAME,USER_EMAIL,ORIGINAL_PROFILENAME,RENAMED_PROFILENAME,USER_PHONE,USER_ROLE,USER_ENROLLDATE,USER_AREA1,USER_AREA2) values ('user17','1234','김강산','she@naver.com','profile1.jpg','profile1.jpg','010-1234-5678','ROLE_USER',to_date('21/12/21','RR/MM/DD'),'부산광역시','수영구');
Insert into QT_USER (USER_ID,USER_PASSWORD,USER_NAME,USER_EMAIL,ORIGINAL_PROFILENAME,RENAMED_PROFILENAME,USER_PHONE,USER_ROLE,USER_ENROLLDATE,USER_AREA1,USER_AREA2) values ('user18','1234','김하늘','she@naver.com','profile1.jpg','profile1.jpg','010-1234-5678','ROLE_USER',to_date('21/12/21','RR/MM/DD'),'강원도','강릉시');
Insert into QT_USER (USER_ID,USER_PASSWORD,USER_NAME,USER_EMAIL,ORIGINAL_PROFILENAME,RENAMED_PROFILENAME,USER_PHONE,USER_ROLE,USER_ENROLLDATE,USER_AREA1,USER_AREA2) values ('user19','1234','정소미','she@naver.com','profile1.jpg','profile1.jpg','010-1234-5678','ROLE_USER',to_date('21/12/21','RR/MM/DD'),'부산광역시','수영구');
Insert into QT_USER (USER_ID,USER_PASSWORD,USER_NAME,USER_EMAIL,ORIGINAL_PROFILENAME,RENAMED_PROFILENAME,USER_PHONE,USER_ROLE,USER_ENROLLDATE,USER_AREA1,USER_AREA2) values ('user20','1234','옥하영','she@naver.com','profile1.jpg','profile1.jpg','010-1234-5678','ROLE_USER',to_date('21/12/21','RR/MM/DD'),'부산광역시','수영구');
Insert into QT_USER (USER_ID,USER_PASSWORD,USER_NAME,USER_EMAIL,ORIGINAL_PROFILENAME,RENAMED_PROFILENAME,USER_PHONE,USER_ROLE,USER_ENROLLDATE,USER_AREA1,USER_AREA2) values ('user21','1234','박혜영','she@naver.com','profile1.jpg','profile1.jpg','010-1234-5678','ROLE_USER',to_date('21/12/21','RR/MM/DD'),'부산광역시','수영구');
Insert into QT_USER (USER_ID,USER_PASSWORD,USER_NAME,USER_EMAIL,ORIGINAL_PROFILENAME,RENAMED_PROFILENAME,USER_PHONE,USER_ROLE,USER_ENROLLDATE,USER_AREA1,USER_AREA2) values ('user22','1234','오현주','she@naver.com','profile1.jpg','profile1.jpg','010-1234-5678','ROLE_USER',to_date('21/12/21','RR/MM/DD'),'부산광역시','수영구');
Insert into QT_USER (USER_ID,USER_PASSWORD,USER_NAME,USER_EMAIL,ORIGINAL_PROFILENAME,RENAMED_PROFILENAME,USER_PHONE,USER_ROLE,USER_ENROLLDATE,USER_AREA1,USER_AREA2) values ('user23','1234','오현민','she@naver.com','profile1.jpg','profile1.jpg','010-1234-5678','ROLE_USER',to_date('21/12/21','RR/MM/DD'),'부산광역시','수영구');
Insert into QT_USER (USER_ID,USER_PASSWORD,USER_NAME,USER_EMAIL,ORIGINAL_PROFILENAME,RENAMED_PROFILENAME,USER_PHONE,USER_ROLE,USER_ENROLLDATE,USER_AREA1,USER_AREA2) values ('user24','1234','문지은','she@naver.com','profile1.jpg','profile1.jpg','010-1234-5678','ROLE_USER',to_date('21/12/21','RR/MM/DD'),'부산광역시','남구');

------------------------------------------------
--------------- 더미 데이터 (보드)-----------------
------------------------------------------------


BEGIN
    FOR N IN 1..52
    LOOP
        INSERT INTO BOARD VALUES(SEQ_BOARD_NO.NEXTVAL, 'admin3', '게시글 ' || SEQ_BOARD_NO.CURRVAL , '큐티마켓 공지사항입니다.' ||  SEQ_BOARD_NO.CURRVAL, SYSDATE, SYSDATE, DEFAULT, NULL, NULL, '공지사항');
    END LOOP;
    
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK;
END;
/



-- COMMIT;

------------------------------------------------
--------------- 더미 데이터 (상품)---------------
------------------------------------------------


INSERT INTO GOODS (
G_PRODUCT,
USER_ID,
G_PRODUCT_NAME,
G_PRICE,
G_CONTENT,
G_DATE,
G_HITS,
G_CATE,
G_O_FILENAME,
G_R_FILENAME,
G_AREA1,
G_AREA2,
STATUS
) VALUES (
'0',
'admin2',
'나이키옷',
'10000',
'새옷같은 옷 판매합니다',
'20211212',
'1',
'clothes',
'null',
'null',
'경기도',
'과천시',
'Y'
);

COMMIT;



